# 훈련 과정에 필요하는 hyperparameter
batch_size: 16
learning_rate: 0.0001   # 0.0005
max_len: 800
min_freq: 20
num_fold: 6
shuffle: True
num_epochs: 20
scheduler_gamma: 0.8
scheduler_step_size: 10
patience: 5
weight_decay: 0.03

# 모델 관련 hyperparameter
n_head: 1 
head_dim: 32 
n_stack: 1 
k: 32 
embedding_dropout: 0.2
attention_dropout: 0.5
ffn_dropout: 0.5
